name: care-appliances

services:
  wordpress:
    image: wordpress:latest
    container_name: care_appliances
    restart: always
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_care_appliances
    volumes:
      - wordpress_data:/var/www/html
      - ./themes:/var/www/html/wp-content/themes
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: care_appliances_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_care_appliances
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
